version: '3.8'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
    - ./:/var/www
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./certs:/etc/nginx/nginx_cert
    ports:
    - 443:443
    networks:
    - my-network
    depends_on:
    - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "api.app:create_app()"
    volumes:
    - ./:/var/www
    networks:
      my-network:
        aliases:
        - flask-app

networks:
  my-network:

